//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdieuchuyenthietbi
    {
        public System.Guid ma { get; set; }
        public string thietbima { get; set; }
        public Nullable<System.Guid> dondcma { get; set; }
        public Nullable<System.Guid> danhgiama { get; set; }
        public Nullable<System.DateTime> ngaydieuchuyen { get; set; }
    
        public virtual dieuchuyentrangthietbi dieuchuyentrangthietbi { get; set; }
        public virtual tinhtrangthietbi tinhtrangthietbi { get; set; }
        public virtual trangthietbi trangthietbi { get; set; }
    }
}
