//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietsuachuathietbi
    {
        public System.Guid ma { get; set; }
        public Nullable<System.Guid> hoadonma { get; set; }
        public string thietbima { get; set; }
        public Nullable<System.DateTime> ngaysuachua { get; set; }
        public string chitiethonghoc { get; set; }
        public string nguoisuachua { get; set; }
        public string ghinhan { get; set; }
    
        public virtual hoadonsuachua hoadonsuachua { get; set; }
        public virtual trangthietbi trangthietbi { get; set; }
    }
}
