//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadonbosung
    {
        public string ma { get; set; }
        public string ten { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<int> cauhinhma { get; set; }
        public Nullable<System.Guid> hoadonma { get; set; }
        public Nullable<bool> ghinhan { get; set; }
    
        public virtual chitietcauhinh chitietcauhinh { get; set; }
        public virtual hoadonmuabosung hoadonmuabosung { get; set; }
    }
}
