//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class dieuchuyentrangthietbi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dieuchuyentrangthietbi()
        {
            this.chitietdieuchuyenthietbi = new HashSet<chitietdieuchuyenthietbi>();
        }
    
        public System.Guid ma { get; set; }
        public string hienthima { get; set; }
        public string nguoidieuchuyen { get; set; }
        public Nullable<System.DateTime> ngaydieuchuyen { get; set; }
        public string phongdima { get; set; }
        public string phongdenma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdieuchuyenthietbi> chitietdieuchuyenthietbi { get; set; }
        public virtual phongmay phongmay { get; set; }
        public virtual phongmay phongmay1 { get; set; }
    }
}
