//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonsuachua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadonsuachua()
        {
            this.chitietsuachuathietbi = new HashSet<chitietsuachuathietbi>();
        }
    
        public System.Guid ma { get; set; }
        public string hienthima { get; set; }
        public string nguoicap { get; set; }
        public Nullable<System.DateTime> ngaycap { get; set; }
        public string donvisuachua { get; set; }
        public string mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietsuachuathietbi> chitietsuachuathietbi { get; set; }
    }
}
