//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class phancaptinhtrang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phancaptinhtrang()
        {
            this.tinhtrangthietbi = new HashSet<tinhtrangthietbi>();
        }
    
        public int ma { get; set; }
        public string tinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tinhtrangthietbi> tinhtrangthietbi { get; set; }
    }
}
