//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLPMN2Entities : DbContext
    {
        public QLPMN2Entities()
            : base("name=QLPMN2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietcauhinh> chitietcauhinh { get; set; }
        public virtual DbSet<chitietdanhgiatrangthietbi> chitietdanhgiatrangthietbi { get; set; }
        public virtual DbSet<chitietdieuchuyenthietbi> chitietdieuchuyenthietbi { get; set; }
        public virtual DbSet<chitietsuachuathietbi> chitietsuachuathietbi { get; set; }
        public virtual DbSet<chitiethoadonbosung> chitiethoadonbosung { get; set; }
        public virtual DbSet<danhgiatrangthietbi> danhgiatrangthietbi { get; set; }
        public virtual DbSet<dieuchuyentrangthietbi> dieuchuyentrangthietbi { get; set; }
        public virtual DbSet<hoadonmuabosung> hoadonmuabosung { get; set; }
        public virtual DbSet<hoadonsuachua> hoadonsuachua { get; set; }
        public virtual DbSet<phancaptinhtrang> phancaptinhtrang { get; set; }
        public virtual DbSet<phongmay> phongmay { get; set; }
        public virtual DbSet<tinhtrangthietbi> tinhtrangthietbi { get; set; }
        public virtual DbSet<trangthietbi> trangthietbi { get; set; }
    
        [DbFunction("QLPMN2Entities", "FC_DanhSachPM")]
        public virtual IQueryable<FC_DanhSachPM_Result> FC_DanhSachPM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FC_DanhSachPM_Result>("[QLPMN2Entities].[FC_DanhSachPM]()");
        }
    
        [DbFunction("QLPMN2Entities", "FC_DIEUCHUYEN_TTB")]
        public virtual IQueryable<FC_DIEUCHUYEN_TTB_Result> FC_DIEUCHUYEN_TTB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FC_DIEUCHUYEN_TTB_Result>("[QLPMN2Entities].[FC_DIEUCHUYEN_TTB]()");
        }
    
        [DbFunction("QLPMN2Entities", "FC_HienThiMayTinhPhongMay")]
        public virtual IQueryable<FC_HienThiMayTinhPhongMay_Result> FC_HienThiMayTinhPhongMay(string maPM)
        {
            var maPMParameter = maPM != null ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FC_HienThiMayTinhPhongMay_Result>("[QLPMN2Entities].[FC_HienThiMayTinhPhongMay](@MaPM)", maPMParameter);
        }
    
        [DbFunction("QLPMN2Entities", "FC_HienThiThietBiTheoThoiGian")]
        public virtual IQueryable<FC_HienThiThietBiTheoThoiGian_Result> FC_HienThiThietBiTheoThoiGian(Nullable<System.DateTime> time1, Nullable<System.DateTime> time2)
        {
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FC_HienThiThietBiTheoThoiGian_Result>("[QLPMN2Entities].[FC_HienThiThietBiTheoThoiGian](@time1, @time2)", time1Parameter, time2Parameter);
        }
    
        [DbFunction("QLPMN2Entities", "FC_HienThiTrangThietBiPhongMay")]
        public virtual IQueryable<FC_HienThiTrangThietBiPhongMay_Result> FC_HienThiTrangThietBiPhongMay(string maPM)
        {
            var maPMParameter = maPM != null ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FC_HienThiTrangThietBiPhongMay_Result>("[QLPMN2Entities].[FC_HienThiTrangThietBiPhongMay](@MaPM)", maPMParameter);
        }
    
        [DbFunction("QLPMN2Entities", "FC_MUCDANHGIA_GANNHAT")]
        public virtual IQueryable<FC_MUCDANHGIA_GANNHAT_Result> FC_MUCDANHGIA_GANNHAT(string mathietbi)
        {
            var mathietbiParameter = mathietbi != null ?
                new ObjectParameter("mathietbi", mathietbi) :
                new ObjectParameter("mathietbi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FC_MUCDANHGIA_GANNHAT_Result>("[QLPMN2Entities].[FC_MUCDANHGIA_GANNHAT](@mathietbi)", mathietbiParameter);
        }
    
        [DbFunction("QLPMN2Entities", "fc_thongkedanhgia")]
        public virtual IQueryable<fc_thongkedanhgia_Result> fc_thongkedanhgia(Nullable<System.Guid> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fc_thongkedanhgia_Result>("[QLPMN2Entities].[fc_thongkedanhgia](@ma)", maParameter);
        }
    
        [DbFunction("QLPMN2Entities", "FC_Thongkedieuchuyen")]
        public virtual IQueryable<FC_Thongkedieuchuyen_Result> FC_Thongkedieuchuyen(Nullable<System.Guid> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FC_Thongkedieuchuyen_Result>("[QLPMN2Entities].[FC_Thongkedieuchuyen](@ma)", maParameter);
        }
    
        public virtual int SP_Bosungthietbivaophongmay(string phongmayma, string ma)
        {
            var phongmaymaParameter = phongmayma != null ?
                new ObjectParameter("phongmayma", phongmayma) :
                new ObjectParameter("phongmayma", typeof(string));
    
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Bosungthietbivaophongmay", phongmaymaParameter, maParameter);
        }
    
        public virtual int SP_CAPNHAT_PHONGMAY(string maPM, string ten)
        {
            var maPMParameter = maPM != null ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHAT_PHONGMAY", maPMParameter, tenParameter);
        }
    
        public virtual int SP_CAPNHATTHIETBISUACHUA(Nullable<System.Guid> idctsc, string matb, Nullable<System.Guid> mahoadon, Nullable<System.DateTime> udngaysuachua, string honghoc, string udnguoisuachua, string udghinhan)
        {
            var idctscParameter = idctsc.HasValue ?
                new ObjectParameter("idctsc", idctsc) :
                new ObjectParameter("idctsc", typeof(System.Guid));
    
            var matbParameter = matb != null ?
                new ObjectParameter("matb", matb) :
                new ObjectParameter("matb", typeof(string));
    
            var mahoadonParameter = mahoadon.HasValue ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(System.Guid));
    
            var udngaysuachuaParameter = udngaysuachua.HasValue ?
                new ObjectParameter("udngaysuachua", udngaysuachua) :
                new ObjectParameter("udngaysuachua", typeof(System.DateTime));
    
            var honghocParameter = honghoc != null ?
                new ObjectParameter("honghoc", honghoc) :
                new ObjectParameter("honghoc", typeof(string));
    
            var udnguoisuachuaParameter = udnguoisuachua != null ?
                new ObjectParameter("udnguoisuachua", udnguoisuachua) :
                new ObjectParameter("udnguoisuachua", typeof(string));
    
            var udghinhanParameter = udghinhan != null ?
                new ObjectParameter("udghinhan", udghinhan) :
                new ObjectParameter("udghinhan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATTHIETBISUACHUA", idctscParameter, matbParameter, mahoadonParameter, udngaysuachuaParameter, honghocParameter, udnguoisuachuaParameter, udghinhanParameter);
        }
    
        public virtual int SP_CAPNHATHOADONSC(Nullable<System.Guid> idhd, string udnguoicap, string udmahienthi, Nullable<System.DateTime> udngaycap, string uddonvisuachua, string udmota)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(System.Guid));
    
            var udnguoicapParameter = udnguoicap != null ?
                new ObjectParameter("udnguoicap", udnguoicap) :
                new ObjectParameter("udnguoicap", typeof(string));
    
            var udmahienthiParameter = udmahienthi != null ?
                new ObjectParameter("udmahienthi", udmahienthi) :
                new ObjectParameter("udmahienthi", typeof(string));
    
            var udngaycapParameter = udngaycap.HasValue ?
                new ObjectParameter("udngaycap", udngaycap) :
                new ObjectParameter("udngaycap", typeof(System.DateTime));
    
            var uddonvisuachuaParameter = uddonvisuachua != null ?
                new ObjectParameter("uddonvisuachua", uddonvisuachua) :
                new ObjectParameter("uddonvisuachua", typeof(string));
    
            var udmotaParameter = udmota != null ?
                new ObjectParameter("udmota", udmota) :
                new ObjectParameter("udmota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATHOADONSC", idhdParameter, udnguoicapParameter, udmahienthiParameter, udngaycapParameter, uddonvisuachuaParameter, udmotaParameter);
        }
    
        public virtual ObjectResult<SP_DANHSACHTBSCTRONGHOADON_Result> SP_DANHSACHTBSCTRONGHOADON(Nullable<System.Guid> hoadonma)
        {
            var hoadonmaParameter = hoadonma.HasValue ?
                new ObjectParameter("hoadonma", hoadonma) :
                new ObjectParameter("hoadonma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DANHSACHTBSCTRONGHOADON_Result>("SP_DANHSACHTBSCTRONGHOADON", hoadonmaParameter);
        }
    
        public virtual ObjectResult<SP_DANHSACHTBSCTRONGNAM_Result> SP_DANHSACHTBSCTRONGNAM(Nullable<int> theyear)
        {
            var theyearParameter = theyear.HasValue ?
                new ObjectParameter("theyear", theyear) :
                new ObjectParameter("theyear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DANHSACHTBSCTRONGNAM_Result>("SP_DANHSACHTBSCTRONGNAM", theyearParameter);
        }
    
        public virtual ObjectResult<SP_HIENTHI_CHITIETDGTTB_Result> SP_HIENTHI_CHITIETDGTTB(Nullable<System.Guid> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HIENTHI_CHITIETDGTTB_Result>("SP_HIENTHI_CHITIETDGTTB", maParameter);
        }
    
        public virtual ObjectResult<SP_HIENTHI_DGTB_THANHLY_Result> SP_HIENTHI_DGTB_THANHLY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HIENTHI_DGTB_THANHLY_Result>("SP_HIENTHI_DGTB_THANHLY");
        }
    
        public virtual ObjectResult<SP_HIENTHI_PHONGMAY_Result> SP_HIENTHI_PHONGMAY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HIENTHI_PHONGMAY_Result>("SP_HIENTHI_PHONGMAY");
        }
    
        public virtual ObjectResult<SP_HIENTHI_THIETBI_CAUHINH_Result> SP_HIENTHI_THIETBI_CAUHINH(string manhinh, string ram, string vixuly, string diacung)
        {
            var manhinhParameter = manhinh != null ?
                new ObjectParameter("manhinh", manhinh) :
                new ObjectParameter("manhinh", typeof(string));
    
            var ramParameter = ram != null ?
                new ObjectParameter("ram", ram) :
                new ObjectParameter("ram", typeof(string));
    
            var vixulyParameter = vixuly != null ?
                new ObjectParameter("vixuly", vixuly) :
                new ObjectParameter("vixuly", typeof(string));
    
            var diacungParameter = diacung != null ?
                new ObjectParameter("diacung", diacung) :
                new ObjectParameter("diacung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HIENTHI_THIETBI_CAUHINH_Result>("SP_HIENTHI_THIETBI_CAUHINH", manhinhParameter, ramParameter, vixulyParameter, diacungParameter);
        }
    
        public virtual ObjectResult<SP_HienThiDanhSachCapNhatTrangThietBi_Result> SP_HienThiDanhSachCapNhatTrangThietBi(string maTTB)
        {
            var maTTBParameter = maTTB != null ?
                new ObjectParameter("MaTTB", maTTB) :
                new ObjectParameter("MaTTB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HienThiDanhSachCapNhatTrangThietBi_Result>("SP_HienThiDanhSachCapNhatTrangThietBi", maTTBParameter);
        }
    
        public virtual ObjectResult<SP_HIENTHIDG_Result> SP_HIENTHIDG(string ma, string ten)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HIENTHIDG_Result>("SP_HIENTHIDG", maParameter, tenParameter);
        }
    
        public virtual ObjectResult<SP_Hienthithietbibosungtheothoigian_Result> SP_Hienthithietbibosungtheothoigian(Nullable<System.DateTime> time1, Nullable<System.DateTime> time2)
        {
            var time1Parameter = time1.HasValue ?
                new ObjectParameter("time1", time1) :
                new ObjectParameter("time1", typeof(System.DateTime));
    
            var time2Parameter = time2.HasValue ?
                new ObjectParameter("time2", time2) :
                new ObjectParameter("time2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Hienthithietbibosungtheothoigian_Result>("SP_Hienthithietbibosungtheothoigian", time1Parameter, time2Parameter);
        }
    
        public virtual ObjectResult<SP_HienThiTrangThietBiPhongMay_Result> SP_HienThiTrangThietBiPhongMay(string maPM)
        {
            var maPMParameter = maPM != null ?
                new ObjectParameter("MaPM", maPM) :
                new ObjectParameter("MaPM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HienThiTrangThietBiPhongMay_Result>("SP_HienThiTrangThietBiPhongMay", maPMParameter);
        }
    
        public virtual int SP_INSERT_chitiethoadonbosung(string ma, string ten, Nullable<decimal> dongia, Nullable<int> cauhinhma, Nullable<System.Guid> hoadonma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(decimal));
    
            var cauhinhmaParameter = cauhinhma.HasValue ?
                new ObjectParameter("cauhinhma", cauhinhma) :
                new ObjectParameter("cauhinhma", typeof(int));
    
            var hoadonmaParameter = hoadonma.HasValue ?
                new ObjectParameter("hoadonma", hoadonma) :
                new ObjectParameter("hoadonma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_chitiethoadonbosung", maParameter, tenParameter, dongiaParameter, cauhinhmaParameter, hoadonmaParameter);
        }
    
        public virtual int SP_INSERT_hoadonmuabosung(string nguoicap, Nullable<System.DateTime> ngaycap, Nullable<int> soluong, string mota, string hienthima)
        {
            var nguoicapParameter = nguoicap != null ?
                new ObjectParameter("nguoicap", nguoicap) :
                new ObjectParameter("nguoicap", typeof(string));
    
            var ngaycapParameter = ngaycap.HasValue ?
                new ObjectParameter("ngaycap", ngaycap) :
                new ObjectParameter("ngaycap", typeof(System.DateTime));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var hienthimaParameter = hienthima != null ?
                new ObjectParameter("hienthima", hienthima) :
                new ObjectParameter("hienthima", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_hoadonmuabosung", nguoicapParameter, ngaycapParameter, soluongParameter, motaParameter, hienthimaParameter);
        }
    
        public virtual ObjectResult<SP_LaychitietDieuchuyen_Result> SP_LaychitietDieuchuyen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LaychitietDieuchuyen_Result>("SP_LaychitietDieuchuyen");
        }
    
        public virtual ObjectResult<SP_LayhoadonDieuchuyen_Result> SP_LayhoadonDieuchuyen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LayhoadonDieuchuyen_Result>("SP_LayhoadonDieuchuyen");
        }
    
        public virtual ObjectResult<SP_SELECT_chitiethoadonmuabosung_Result> SP_SELECT_chitiethoadonmuabosung(Nullable<System.Guid> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_chitiethoadonmuabosung_Result>("SP_SELECT_chitiethoadonmuabosung", maParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SoLanCapNhatTrangThai(string maTTB)
        {
            var maTTBParameter = maTTB != null ?
                new ObjectParameter("MaTTB", maTTB) :
                new ObjectParameter("MaTTB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SoLanCapNhatTrangThai", maTTBParameter);
        }
    
        public virtual int SP_SUACTDGTTB(string thietbima, string capchatluong, string ketqua, Nullable<System.DateTime> thoigian)
        {
            var thietbimaParameter = thietbima != null ?
                new ObjectParameter("thietbima", thietbima) :
                new ObjectParameter("thietbima", typeof(string));
    
            var capchatluongParameter = capchatluong != null ?
                new ObjectParameter("capchatluong", capchatluong) :
                new ObjectParameter("capchatluong", typeof(string));
    
            var ketquaParameter = ketqua != null ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(string));
    
            var thoigianParameter = thoigian.HasValue ?
                new ObjectParameter("thoigian", thoigian) :
                new ObjectParameter("thoigian", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SUACTDGTTB", thietbimaParameter, capchatluongParameter, ketquaParameter, thoigianParameter);
        }
    
        public virtual int SP_SuahoadonDieuchuyen(Nullable<System.Guid> ma, string hienthima, string nguoidieuchuyen, Nullable<System.DateTime> ngaydieuchuyen, string phongdima, string phongdenma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            var hienthimaParameter = hienthima != null ?
                new ObjectParameter("hienthima", hienthima) :
                new ObjectParameter("hienthima", typeof(string));
    
            var nguoidieuchuyenParameter = nguoidieuchuyen != null ?
                new ObjectParameter("nguoidieuchuyen", nguoidieuchuyen) :
                new ObjectParameter("nguoidieuchuyen", typeof(string));
    
            var ngaydieuchuyenParameter = ngaydieuchuyen.HasValue ?
                new ObjectParameter("ngaydieuchuyen", ngaydieuchuyen) :
                new ObjectParameter("ngaydieuchuyen", typeof(System.DateTime));
    
            var phongdimaParameter = phongdima != null ?
                new ObjectParameter("phongdima", phongdima) :
                new ObjectParameter("phongdima", typeof(string));
    
            var phongdenmaParameter = phongdenma != null ?
                new ObjectParameter("phongdenma", phongdenma) :
                new ObjectParameter("phongdenma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuahoadonDieuchuyen", maParameter, hienthimaParameter, nguoidieuchuyenParameter, ngaydieuchuyenParameter, phongdimaParameter, phongdenmaParameter);
        }
    
        public virtual ObjectResult<SP_TimKiemTheoMaTTB_Result> SP_TimKiemTheoMaTTB(string maTTB)
        {
            var maTTBParameter = maTTB != null ?
                new ObjectParameter("MaTTB", maTTB) :
                new ObjectParameter("MaTTB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TimKiemTheoMaTTB_Result>("SP_TimKiemTheoMaTTB", maTTBParameter);
        }
    
        public virtual int SP_THEM_PHONGMAY(string ma, string ten, Nullable<int> soluong)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEM_PHONGMAY", maParameter, tenParameter, soluongParameter);
        }
    
        public virtual int SP_THEMCTDGTTB(string thietbima, string capchatluong, string ketqua, Nullable<System.Guid> danhgiama, Nullable<System.DateTime> thoigian)
        {
            var thietbimaParameter = thietbima != null ?
                new ObjectParameter("thietbima", thietbima) :
                new ObjectParameter("thietbima", typeof(string));
    
            var capchatluongParameter = capchatluong != null ?
                new ObjectParameter("capchatluong", capchatluong) :
                new ObjectParameter("capchatluong", typeof(string));
    
            var ketquaParameter = ketqua != null ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(string));
    
            var danhgiamaParameter = danhgiama.HasValue ?
                new ObjectParameter("danhgiama", danhgiama) :
                new ObjectParameter("danhgiama", typeof(System.Guid));
    
            var thoigianParameter = thoigian.HasValue ?
                new ObjectParameter("thoigian", thoigian) :
                new ObjectParameter("thoigian", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMCTDGTTB", thietbimaParameter, capchatluongParameter, ketquaParameter, danhgiamaParameter, thoigianParameter);
        }
    
        public virtual int SP_THEMDGTTB(string ma, string nguoidanhgia, Nullable<System.DateTime> ngaydanhgia, string mota)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var nguoidanhgiaParameter = nguoidanhgia != null ?
                new ObjectParameter("nguoidanhgia", nguoidanhgia) :
                new ObjectParameter("nguoidanhgia", typeof(string));
    
            var ngaydanhgiaParameter = ngaydanhgia.HasValue ?
                new ObjectParameter("ngaydanhgia", ngaydanhgia) :
                new ObjectParameter("ngaydanhgia", typeof(System.DateTime));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMDGTTB", maParameter, nguoidanhgiaParameter, ngaydanhgiaParameter, motaParameter);
        }
    
        public virtual int SP_ThemhoadonDieuchuyen(string hienthima, string nguoidieuchuyen, Nullable<System.DateTime> ngaydieuchuyen, string phongdima, string phongdenma)
        {
            var hienthimaParameter = hienthima != null ?
                new ObjectParameter("hienthima", hienthima) :
                new ObjectParameter("hienthima", typeof(string));
    
            var nguoidieuchuyenParameter = nguoidieuchuyen != null ?
                new ObjectParameter("nguoidieuchuyen", nguoidieuchuyen) :
                new ObjectParameter("nguoidieuchuyen", typeof(string));
    
            var ngaydieuchuyenParameter = ngaydieuchuyen.HasValue ?
                new ObjectParameter("ngaydieuchuyen", ngaydieuchuyen) :
                new ObjectParameter("ngaydieuchuyen", typeof(System.DateTime));
    
            var phongdimaParameter = phongdima != null ?
                new ObjectParameter("phongdima", phongdima) :
                new ObjectParameter("phongdima", typeof(string));
    
            var phongdenmaParameter = phongdenma != null ?
                new ObjectParameter("phongdenma", phongdenma) :
                new ObjectParameter("phongdenma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemhoadonDieuchuyen", hienthimaParameter, nguoidieuchuyenParameter, ngaydieuchuyenParameter, phongdimaParameter, phongdenmaParameter);
        }
    
        public virtual int SP_THEMMOIHOADONSC(string nguoicap, string mahienthi, Nullable<System.DateTime> ngaycap, string donvisuachua, string mota)
        {
            var nguoicapParameter = nguoicap != null ?
                new ObjectParameter("nguoicap", nguoicap) :
                new ObjectParameter("nguoicap", typeof(string));
    
            var mahienthiParameter = mahienthi != null ?
                new ObjectParameter("mahienthi", mahienthi) :
                new ObjectParameter("mahienthi", typeof(string));
    
            var ngaycapParameter = ngaycap.HasValue ?
                new ObjectParameter("ngaycap", ngaycap) :
                new ObjectParameter("ngaycap", typeof(System.DateTime));
    
            var donvisuachuaParameter = donvisuachua != null ?
                new ObjectParameter("donvisuachua", donvisuachua) :
                new ObjectParameter("donvisuachua", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMMOIHOADONSC", nguoicapParameter, mahienthiParameter, ngaycapParameter, donvisuachuaParameter, motaParameter);
        }
    
        public virtual int SP_THEMMOITHIETBISUACHUA(Nullable<System.DateTime> ngaysuachua, string nguoisuachua, Nullable<System.Guid> hoadonma, string thietbima, string chitiethong, string ghinhan)
        {
            var ngaysuachuaParameter = ngaysuachua.HasValue ?
                new ObjectParameter("ngaysuachua", ngaysuachua) :
                new ObjectParameter("ngaysuachua", typeof(System.DateTime));
    
            var nguoisuachuaParameter = nguoisuachua != null ?
                new ObjectParameter("nguoisuachua", nguoisuachua) :
                new ObjectParameter("nguoisuachua", typeof(string));
    
            var hoadonmaParameter = hoadonma.HasValue ?
                new ObjectParameter("hoadonma", hoadonma) :
                new ObjectParameter("hoadonma", typeof(System.Guid));
    
            var thietbimaParameter = thietbima != null ?
                new ObjectParameter("thietbima", thietbima) :
                new ObjectParameter("thietbima", typeof(string));
    
            var chitiethongParameter = chitiethong != null ?
                new ObjectParameter("chitiethong", chitiethong) :
                new ObjectParameter("chitiethong", typeof(string));
    
            var ghinhanParameter = ghinhan != null ?
                new ObjectParameter("ghinhan", ghinhan) :
                new ObjectParameter("ghinhan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMMOITHIETBISUACHUA", ngaysuachuaParameter, nguoisuachuaParameter, hoadonmaParameter, thietbimaParameter, chitiethongParameter, ghinhanParameter);
        }
    
        public virtual ObjectResult<SP_THONGKE_DGTB_Result> SP_THONGKE_DGTB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKE_DGTB_Result>("SP_THONGKE_DGTB");
        }
    
        public virtual ObjectResult<SP_THONGKE_DSCHITIET_THIETBISUACHUA_Result> SP_THONGKE_DSCHITIET_THIETBISUACHUA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKE_DSCHITIET_THIETBISUACHUA_Result>("SP_THONGKE_DSCHITIET_THIETBISUACHUA");
        }
    
        public virtual ObjectResult<SP_THONGKE_DSDIEUCHUYENTB_Result> SP_THONGKE_DSDIEUCHUYENTB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKE_DSDIEUCHUYENTB_Result>("SP_THONGKE_DSDIEUCHUYENTB");
        }
    
        public virtual ObjectResult<SP_THONGKE_DSSUACHUATHIETBI_Result> SP_THONGKE_DSSUACHUATHIETBI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKE_DSSUACHUATHIETBI_Result>("SP_THONGKE_DSSUACHUATHIETBI");
        }
    
        public virtual ObjectResult<SP_THONGKE_DSTTB_Result> SP_THONGKE_DSTTB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKE_DSTTB_Result>("SP_THONGKE_DSTTB");
        }
    
        public virtual ObjectResult<SP_THONGKEPHANCAP_CHITIET_Result> SP_THONGKEPHANCAP_CHITIET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKEPHANCAP_CHITIET_Result>("SP_THONGKEPHANCAP_CHITIET");
        }
    
        public virtual ObjectResult<SP_THONGKESOLUONG_MAYDC_Result> SP_THONGKESOLUONG_MAYDC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKESOLUONG_MAYDC_Result>("SP_THONGKESOLUONG_MAYDC");
        }
    
        public virtual ObjectResult<SP_THONGKESOLUONG_PHUONGMAY_Result> SP_THONGKESOLUONG_PHUONGMAY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKESOLUONG_PHUONGMAY_Result>("SP_THONGKESOLUONG_PHUONGMAY");
        }
    
        public virtual ObjectResult<SP_THONGKESUACHUA_CHUASUA_Result> SP_THONGKESUACHUA_CHUASUA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKESUACHUA_CHUASUA_Result>("SP_THONGKESUACHUA_CHUASUA");
        }
    
        public virtual ObjectResult<SP_THONGKESUACHUA_SUATREN5_Result> SP_THONGKESUACHUA_SUATREN5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGKESUACHUA_SUATREN5_Result>("SP_THONGKESUACHUA_SUATREN5");
        }
    
        public virtual ObjectResult<SP_THONGTINTHIETBISUACHUA_Result> SP_THONGTINTHIETBISUACHUA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THONGTINTHIETBISUACHUA_Result>("SP_THONGTINTHIETBISUACHUA");
        }
    
        public virtual int SP_UPDATE_hoadonmuabosung(string nguoicap, Nullable<System.DateTime> ngaycap, Nullable<int> soluong, string mota, string mahienthi)
        {
            var nguoicapParameter = nguoicap != null ?
                new ObjectParameter("nguoicap", nguoicap) :
                new ObjectParameter("nguoicap", typeof(string));
    
            var ngaycapParameter = ngaycap.HasValue ?
                new ObjectParameter("ngaycap", ngaycap) :
                new ObjectParameter("ngaycap", typeof(System.DateTime));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var mahienthiParameter = mahienthi != null ?
                new ObjectParameter("mahienthi", mahienthi) :
                new ObjectParameter("mahienthi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_hoadonmuabosung", nguoicapParameter, ngaycapParameter, soluongParameter, motaParameter, mahienthiParameter);
        }
    
        public virtual int SP_UPDATEANDINSERT_DIEUCHUYENTHIETBI(Nullable<System.Guid> ma, string hienthima, string nguoidieuchuyen, Nullable<System.DateTime> ngaydieuchuyen, string phongdima, string phongdenma, Nullable<bool> flag)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            var hienthimaParameter = hienthima != null ?
                new ObjectParameter("hienthima", hienthima) :
                new ObjectParameter("hienthima", typeof(string));
    
            var nguoidieuchuyenParameter = nguoidieuchuyen != null ?
                new ObjectParameter("nguoidieuchuyen", nguoidieuchuyen) :
                new ObjectParameter("nguoidieuchuyen", typeof(string));
    
            var ngaydieuchuyenParameter = ngaydieuchuyen.HasValue ?
                new ObjectParameter("ngaydieuchuyen", ngaydieuchuyen) :
                new ObjectParameter("ngaydieuchuyen", typeof(System.DateTime));
    
            var phongdimaParameter = phongdima != null ?
                new ObjectParameter("phongdima", phongdima) :
                new ObjectParameter("phongdima", typeof(string));
    
            var phongdenmaParameter = phongdenma != null ?
                new ObjectParameter("phongdenma", phongdenma) :
                new ObjectParameter("phongdenma", typeof(string));
    
            var flagParameter = flag.HasValue ?
                new ObjectParameter("flag", flag) :
                new ObjectParameter("flag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATEANDINSERT_DIEUCHUYENTHIETBI", maParameter, hienthimaParameter, nguoidieuchuyenParameter, ngaydieuchuyenParameter, phongdimaParameter, phongdenmaParameter, flagParameter);
        }
    
        public virtual int SP_UpdateTinhTrangThietBi(string thietbima, Nullable<int> tinhtrangma, Nullable<System.DateTime> ngaydanhgia, string nguoidanhgia, string mota)
        {
            var thietbimaParameter = thietbima != null ?
                new ObjectParameter("thietbima", thietbima) :
                new ObjectParameter("thietbima", typeof(string));
    
            var tinhtrangmaParameter = tinhtrangma.HasValue ?
                new ObjectParameter("tinhtrangma", tinhtrangma) :
                new ObjectParameter("tinhtrangma", typeof(int));
    
            var ngaydanhgiaParameter = ngaydanhgia.HasValue ?
                new ObjectParameter("ngaydanhgia", ngaydanhgia) :
                new ObjectParameter("ngaydanhgia", typeof(System.DateTime));
    
            var nguoidanhgiaParameter = nguoidanhgia != null ?
                new ObjectParameter("nguoidanhgia", nguoidanhgia) :
                new ObjectParameter("nguoidanhgia", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateTinhTrangThietBi", thietbimaParameter, tinhtrangmaParameter, ngaydanhgiaParameter, nguoidanhgiaParameter, motaParameter);
        }
    
        public virtual int SP_XOA_PHONGMAY(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOA_PHONGMAY", maParameter);
        }
    
        public virtual int SP_Xoachitietdieuchuyen(Nullable<System.Guid> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Xoachitietdieuchuyen", maParameter);
        }
    
        public virtual int SP_XoahoadonDieuchuyen(Nullable<System.Guid> ma)
        {
            var maParameter = ma.HasValue ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XoahoadonDieuchuyen", maParameter);
        }
    }
}
