//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tinhtrangthietbi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tinhtrangthietbi()
        {
            this.chitietdieuchuyenthietbi = new HashSet<chitietdieuchuyenthietbi>();
        }
    
        public System.Guid ma { get; set; }
        public string thietbima { get; set; }
        public Nullable<int> tinhtrangma { get; set; }
        public string nguoidanhgia { get; set; }
        public Nullable<System.DateTime> ngaydanhgia { get; set; }
        public string mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdieuchuyenthietbi> chitietdieuchuyenthietbi { get; set; }
        public virtual phancaptinhtrang phancaptinhtrang { get; set; }
        public virtual trangthietbi trangthietbi { get; set; }
    }
}
