//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQLPhongMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class trangthietbi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trangthietbi()
        {
            this.chitietdanhgiatrangthietbi = new HashSet<chitietdanhgiatrangthietbi>();
            this.chitietdieuchuyenthietbi = new HashSet<chitietdieuchuyenthietbi>();
            this.chitietsuachuathietbi = new HashSet<chitietsuachuathietbi>();
            this.tinhtrangthietbi = new HashSet<tinhtrangthietbi>();
        }
    
        public string ma { get; set; }
        public string ten { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> cauhinhma { get; set; }
        public string phongmayma { get; set; }
    
        public virtual chitietcauhinh chitietcauhinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdanhgiatrangthietbi> chitietdanhgiatrangthietbi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdieuchuyenthietbi> chitietdieuchuyenthietbi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietsuachuathietbi> chitietsuachuathietbi { get; set; }
        public virtual phongmay phongmay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tinhtrangthietbi> tinhtrangthietbi { get; set; }
    }
}
